/**
 * Generates Arduino C++ code based on the circuit graph.
 */
export const generateArduinoCode = (nodes, edges) => {
    let includes = new Set();
    let globals = [];
    let setupCode = [];
    let loopCode = [];

    // Helper to find connected pin on the controller (Uno/Nano/ESP32)
    const findControllerPin = (componentNodeId) => {
        const edge = edges.find(e => e.target === componentNodeId || e.source === componentNodeId);
        if (!edge) return null;

        // Assume the other end is the controller
        const isTarget = edge.target === componentNodeId;
        const controllerId = isTarget ? edge.source : edge.target;
        const controllerPin = isTarget ? edge.sourceHandle : edge.targetHandle;

        // Simple check if it's a controller (could be more robust)
        if (controllerId.includes('arduino') || controllerId.includes('esp32')) {
            return controllerPin;
        }
        return null;
    };

    nodes.forEach(node => {
        if (node.type === 'servoMotor') {
            includes.add('#include <Servo.h>');
            const name = `servo_${node.id.replace(/\D/g, '')}`; // servo_1
            globals.push(`Servo ${name};`);

            // Find signal pin connection
            const signalEdge = edges.find(e =>
                (e.target === node.id && e.targetHandle === 'SIG') ||
                (e.source === node.id && e.sourceHandle === 'SIG')
            );

            if (signalEdge) {
                const controllerPin = signalEdge.source === node.id ? signalEdge.targetHandle : signalEdge.sourceHandle;
                // Clean pin name (e.g., "D9" -> "9")
                const pin = controllerPin.replace('D', '');
                setupCode.push(`  ${name}.attach(${pin});`);
            }
        }

        // Basic Stepper logic (placeholder)
        if (node.type === 'stepperMotor') {
            includes.add('#include <Stepper.h>');
            // complex wiring logic omitted for brevity, assuming standard 4-pin
        }
    });

    return `// Generated by Arduino Simulator
${Array.from(includes).join('\n')}

${globals.join('\n')}

void setup() {
${setupCode.join('\n')}
}

void loop() {
  // Your code here
}
`;
};
